version: '3'

services:
  api-beverages:
    container_name: api
    build: .
    command: yarn dev
    volumes:
      - .:/home/app/api-beverages
      - /home/app/api-beverages/node_modules
    depends_on:
      - postgres-beverages
    networks:
      - app-connect
    ports:
      - '5000:5000'

  postgres-beverages:
    container_name: postgres-beverages
    image: postgres:13
    restart: unless-stopped
    volumes:
      - postgres-data:/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - app-connect

  redis-beverages:
    container_name: redis-beverages
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - app-connect

volumes:
  postgres-data:

networks:
  app-connect:
    driver: bridge
