version: '3'

services:

  api:
    container_name: api
    build: .
    command: yarn dev
    volumes:
      - .:/home/app/api
    depends_on:
      - postgres
    networks:
      - app-connect
    ports:
      - '3000:3000'

  postgres:
    container_name: postgres
    image: postgres:13
    restart: unless-stopped
    volumes:
      - postgres-data:/data
    ports: 
      - '5432:5432'
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS} 
    networks:
      - app-connect

volumes:
  postgres-data:

networks:
  app-connect:
      driver: bridge